# Generated by Django 3.2.18 on 2023-05-09 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('enroll', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='students/')),
                ('email', models.EmailField(default='abc@example.com', max_length=50)),
                ('mobile', models.CharField(default='+911234567890', max_length=15)),
                ('encoding', models.CharField(max_length=384050)),
            ],
        ),
        migrations.CreateModel(
            name='System_Admin',
            fields=[
                ('dpt_name', models.CharField(max_length=50)),
                ('hod_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='abc@example.com', max_length=50)),
                ('mobile', models.CharField(default='+911234567890', max_length=15)),
                ('subjects', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='team/')),
            ],
        ),
        migrations.CreateModel(
            name='Third_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.IntegerField(default=0)),
                ('sub2', models.IntegerField(default=0)),
                ('sub3', models.IntegerField(default=0)),
                ('sub4', models.IntegerField(default=0)),
                ('sub5', models.IntegerField(default=0)),
                ('sub6', models.IntegerField(default=0)),
                ('sub7', models.IntegerField(default=0)),
                ('sub8', models.IntegerField(default=0)),
                ('sub9', models.IntegerField(default=0)),
                ('sub10', models.IntegerField(default=0)),
                ('enroll_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.class')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.IntegerField(default=0)),
                ('sub2', models.IntegerField(default=0)),
                ('sub3', models.IntegerField(default=0)),
                ('sub4', models.IntegerField(default=0)),
                ('sub5', models.IntegerField(default=0)),
                ('sub6', models.IntegerField(default=0)),
                ('sub7', models.IntegerField(default=0)),
                ('sub8', models.IntegerField(default=0)),
                ('sub9', models.IntegerField(default=0)),
                ('sub10', models.IntegerField(default=0)),
                ('class_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.class')),
            ],
        ),
        migrations.CreateModel(
            name='Second_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.IntegerField(default=0)),
                ('sub2', models.IntegerField(default=0)),
                ('sub3', models.IntegerField(default=0)),
                ('sub4', models.IntegerField(default=0)),
                ('sub5', models.IntegerField(default=0)),
                ('sub6', models.IntegerField(default=0)),
                ('sub7', models.IntegerField(default=0)),
                ('sub8', models.IntegerField(default=0)),
                ('sub9', models.IntegerField(default=0)),
                ('sub10', models.IntegerField(default=0)),
                ('enroll_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject', models.CharField(max_length=50)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.class')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forget_password_token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Final_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.IntegerField(default=0)),
                ('sub2', models.IntegerField(default=0)),
                ('sub3', models.IntegerField(default=0)),
                ('sub4', models.IntegerField(default=0)),
                ('sub5', models.IntegerField(default=0)),
                ('sub6', models.IntegerField(default=0)),
                ('sub7', models.IntegerField(default=0)),
                ('sub8', models.IntegerField(default=0)),
                ('sub9', models.IntegerField(default=0)),
                ('sub10', models.IntegerField(default=0)),
                ('enroll_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('room', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.class')),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camera_ip', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('status', models.CharField(default='0', max_length=10)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.class')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.classroom')),
            ],
        ),
    ]
