# Generated by Django 3.2.18 on 2023-02-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_name', models.CharField(max_length=100)),
                ('dpt_name', models.CharField(max_length=50)),
                ('hod_name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
