# Generated by Django 3.2.18 on 2023-02-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='id',
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default='password', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='mail',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
