# Generated by Django 3.2.18 on 2023-02-25 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20230225_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='mail',
            new_name='email',
        ),
    ]
