# Generated by Django 3.2.18 on 2023-02-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_rename_mail_admin_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='clg_name',
        ),
    ]
