# Generated by Django 3.2.18 on 2023-02-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='enroll',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
