# Generated by Django 3.2.18 on 2023-02-27 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20230227_1144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='System_Admin',
        ),
    ]
