# Generated by Django 3.2.18 on 2023-04-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_auto_20230402_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(default='+911234567890', max_length=15),
        ),
    ]
