# Generated by Django 3.2.18 on 2023-04-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_alter_student_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='abc@example.com', max_length=50)),
                ('mobile', models.CharField(default='+911234567890', max_length=15)),
                ('subjects', models.CharField(max_length=100)),
            ],
        ),
    ]
