# Generated by Django 3.2.18 on 2023-04-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_alter_student_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='encoding',
            field=models.JSONField(blank=True, default='na'),
        ),
    ]
