# Generated by Django 3.2.18 on 2023-04-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0017_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('room', models.CharField(max_length=5)),
                ('cameraIP', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('status', models.BinaryField()),
                ('classID', models.CharField(max_length=5)),
            ],
        ),
    ]
