# Generated by Django 3.2.18 on 2023-04-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0019_auto_20230418_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
