# Generated by Django 3.2.18 on 2023-04-20 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0020_alter_classroom_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='teacher_id',
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.teacher')),
            ],
        ),
    ]
