# Generated by Django 3.2.18 on 2023-04-20 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0021_auto_20230420_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.subject'),
        ),
    ]
