# Generated by Django 3.2.18 on 2023-04-07 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0021_alter_student_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='encoding',
        ),
    ]
