# Generated by Django 3.2.18 on 2023-04-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0022_alter_schedule_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
