# Generated by Django 3.2.18 on 2023-04-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0023_alter_schedule_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
