# Generated by Django 3.2.18 on 2023-04-22 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0024_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='class_id',
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.classroom')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.class')),
            ],
        ),
    ]
