# Generated by Django 3.2.18 on 2023-04-07 04:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0024_alter_student_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='encoding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=8, default=98.8888, max_digits=11), size=None),
        ),
    ]
