# Generated by Django 3.2.18 on 2023-04-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0026_alter_student_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='encoding',
            field=models.CharField(max_length=2100),
        ),
    ]
