# Generated by Django 3.2.18 on 2023-04-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0028_auto_20230422_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
