# Generated by Django 3.2.18 on 2023-04-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0029_alter_camera_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
