# Generated by Django 3.2.18 on 2023-04-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0023_alter_schedule_subject'),
        ('testapp', '0030_alter_student_encoding'),
    ]

    operations = [
    ]
