# Generated by Django 3.2.18 on 2023-04-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0031_classroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
