# Generated by Django 3.2.18 on 2023-04-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0032_delete_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('room', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.class')),
            ],
        ),
    ]
