# Generated by Django 3.2.18 on 2023-04-23 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0031_merge_20230421_1348'),
        ('testapp', '0033_classroom'),
    ]

    operations = [
    ]
