# Generated by Django 3.2.18 on 2023-04-23 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0033_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='room_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='testapp.classroom'),
            preserve_default=False,
        ),
    ]
