# Generated by Django 3.2.18 on 2023-04-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0034_camera_room_id'),
        ('testapp', '0034_merge_0031_merge_20230421_1348_0033_classroom'),
    ]

    operations = [
    ]
