# Generated by Django 3.2.18 on 2023-04-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0035_merge_20230424_1548'),
        ('testapp', '0035_subject_class_id'),
    ]

    operations = [
    ]
