# Generated by Django 3.2.18 on 2023-04-27 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0037_rename_fourth_year_final_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final_year',
            name='id',
        ),
        migrations.RemoveField(
            model_name='second_year',
            name='id',
        ),
        migrations.RemoveField(
            model_name='third_year',
            name='id',
        ),
        migrations.AlterField(
            model_name='final_year',
            name='enroll_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='testapp.student'),
        ),
        migrations.AlterField(
            model_name='second_year',
            name='enroll_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='testapp.student'),
        ),
        migrations.AlterField(
            model_name='third_year',
            name='enroll_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='testapp.student'),
        ),
    ]
