# Generated by Django 3.2.18 on 2023-04-30 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0036_merge_0035_merge_20230424_1548_0035_subject_class_id'),
        ('testapp', '0039_auto_20230428_1132'),
    ]

    operations = [
    ]
