# Generated by Django 3.2.18 on 2023-05-04 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0040_merge_20230430_1845'),
        ('testapp', '0040_sub_tracker'),
    ]

    operations = [
    ]
